version: '3.8'

services:

  hmny:
    image: ${docker_registry}/hmny:latest
    container_name: hmny
    network_mode: host
    restart: unless-stopped
    # ports:
    #   - 9500:9500 # s0 rpc: one node
    #   - 5099:5099 # s0 explorer

  icon:
    image: ${docker_registry}/icon:latest
    container_name: icon
    network_mode: host
    restart: unless-stopped
    # ports:
    #   - 9080:9080